In [47]:
# Lesson 7
# Task 1
import numpy

A = numpy.array([[1, 2, 3], [4, 0, 6], [7, 8, 9]])
B = numpy.array([12, 2, 1])
numpy.linalg.solve(A, B)

array([-9.2       ,  0.9       ,  6.46666667])

In [45]:
# Lesson 7
# Task 2
import numpy

A = numpy.array([[1, 2, -1], [3, -4, 0], [8, -5, 2], [2, 0, -5], [11, 4, -7]], float)
B = numpy.array([1, 7, 12, 7, 15])  
numpy.linalg.lstsq(A, B, rcond=None)[0]

array([ 1.13919353, -0.90498444, -0.9009803 ])

In [43]:
# Lesson 7
# Task 3.1
import numpy

A = numpy.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B = numpy.array([[12, 2, 1]])
C = numpy.concatenate((A,B.T), axis=1)
print (C)
numpy.linalg.matrix_rank(A, 0.0001), numpy.linalg.matrix_rank(C, 0.0001)

# ранг матрицы А не равен рангу матрицы С, следовательно в таком виде система не имеет решений

[[ 1  2  3 12]
 [ 4  5  6  2]
 [ 7  8  9  1]]


(2, 3)

In [54]:
# Lesson 7
# Task 3.2
import numpy

A = numpy.array([[1, 2, 3], [4, 0, 6], [7, 8, 9]])
B = numpy.array([3, 2, 1])
 
numpy.linalg.solve(A, B)

# ранг матрицы А равен рангу матрицы С (3), следовательно в таком виде система имеет решения

array([-2.00000000e+00,  1.45716772e-16,  1.66666667e+00])

In [57]:
# Lesson 7
# Task 4
import numpy
import scipy
import scipy.linalg

A = numpy.array([ [1, 2, 3], [2, 16, 21], [4, 28, 73]])
P, L, U = scipy.linalg.lu(A)

print(P)
print(L)
print(U)

print(numpy.dot(P.transpose(), A) - numpy.dot(L, U))

[[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]
[[ 1.    0.    0.  ]
 [ 0.25  1.    0.  ]
 [ 0.5  -0.4   1.  ]]
[[  4.    28.    73.  ]
 [  0.    -5.   -15.25]
 [  0.     0.   -21.6 ]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [77]:
# Lesson 7
# Task 5
from mpl_toolkits.mplot3d import Axes3D
import numpy
import matplotlib.pyplot as plot

# найдем нормальное псевдорешение
A = numpy.array([[1,2,-1],[8,-5,2]])
B = numpy.array([1,12])
numpy.linalg.lstsq(A, B, rcond=None)
# (array([ 1.38191882, -0.18081181,  0.0202952 ]),
#  array([], dtype=float64),
#  2,
#  array([9.65316119, 2.41173777]))

# def Q(x, y, z):
#     return (x ** 2 + y ** 2 + z ** 2)

# создаём полотно для рисунка
fig = plot.figure(figsize = (10, 10))

# создаём рисунок пространства с поверхностью
ax = fig.add_subplot(1, 1, 1, projection='3d')

X = numpy.arange(-50, 50, 1)
Y = numpy.arange(-50, 50, 1)
X, Y = numpy.meshgrid(X, Y)

ax.plot_surface(X,Y,Z,color='cyan')
ax.plot_surface(X,Y,Z2,color='green')

# какие значения передаются в Q?
# ax.plot_surface(X, Y, Q(?), cmap=plot.cm.plasma)

(array([ 1.38191882, -0.18081181,  0.0202952 ]),
 array([], dtype=float64),
 2,
 array([9.65316119, 2.41173777]))

In [79]:
# Lesson 7
# Task 6
import numpy

A = numpy.array([ [1, 2, 3], [4, 5, 6], [7, 8, 9] ])
B = numpy.array([2, 5, 11])
Q, R = numpy.linalg.qr(A)
 
print(A)
print(Q)
print(R)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[-0.12309149  0.90453403  0.40824829]
 [-0.49236596  0.30151134 -0.81649658]
 [-0.86164044 -0.30151134  0.40824829]]
[[-8.12403840e+00 -9.60113630e+00 -1.10782342e+01]
 [ 0.00000000e+00  9.04534034e-01  1.80906807e+00]
 [ 0.00000000e+00  0.00000000e+00 -8.88178420e-16]]
